### ISSUE TITLE
funtoo ebuild should be pushed to flora

### ISSUE THREAD

**Issue by funkycode** [limansky/tinymount#1]
Can you push ebuild to flora (https://github.com/funtoo/flora/wiki) or if you don't want i can try to do it. 
thanks

**Comment by limansky** [comment]
Hi,

  Could you please clarify about git flow? Is it some funtoo specific tool, or it's a just a set of scripts to automate work with git, so I can use it from gentoo?

**Comment by funkycode** [comment]
Funtoo portage is using git instead of rsync. Btw as far as i know gentoo in it's way too. And flora in kinda new way of overlwys

**Comment by funkycode** [comment]
as well you can update to funtoo from gentoo.

**Comment by limansky** [comment]
Hm.. I've tried with git-flow. Looks like there some error in the wiki:
 git merge master/develop -- this step is not valid. does it mean that i should merge upstream/master on develop?

And after all I've got a crappy commits. Is it possible to not use git flow, but just commit ebuilds and perform pull request?

**Comment by limansky** [comment]
Done: https://github.com/funtoo/flora/pull/114

**Comment by funkycode** [comment]
thanx. there is a problem in wiki you can ask help on #funtoo chan. i was helped there.

**Comment by funkycode** [comment]
btw i think you should hardmask 9999 or set it without keywords? or maybe to use profile mask (as in funtoo it's a separete dir and not one file, you can just make one for tinymount). 

thanx =P

**Comment by limansky** [comment]
Yes, I just forgot about it.
