### ISSUE TITLE
Qt5 support

### ISSUE THREAD

**Issue by stevenhoneyman** [limansky/tinymount#12]
Could you please add Qt5 support? The only thing that needs to change is in src/src.pro:

`QT += dbus` --> `QT += dbus widgets`

But I'm not very familiar with qmake so not sure how to do a "if qt5 then QT+=widgets" type command
Manually adding it in and it compiles and runs perfectly

**Comment by stevenhoneyman** [comment]
```
greaterThan(QT_VERSION, 4): QT += widgets
```

Just happened to see it in someone elses code :)

**Comment by limansky** [comment]
Hi, thanks for the report. 
Did you tested this solution? I don't have Qt5 installed on my box to test it.

**Comment by stevenhoneyman** [comment]
Yes, just checked, and confirmed the "greaterThan" check works fine on Qt5 - so if it works on your Qt4 as well (with this addition), then it is all OK.

``` diff
diff -urb a/tinymount/src/src.pro b/tinymount/src/src.pro
--- a/tinymount/src/src.pro 2014-08-17 19:51:15.497484385 +0100
+++ b/tinymount/src/src.pro 2014-08-17 19:52:49.064150659 +0100
@@ -37,6 +37,7 @@
 DATADIR = $$PREFIX/share/tinymount

 QT += dbus
+greaterThan(QT_VERSION, 4): QT += widgets

 # Input
 SOURCES = \
```
