### ISSUE TITLE
Any plans to update to Qt5?

### ISSUE THREAD

**Issue by ghost** [limansky/tinymount#14]
Gentoo ebuild stopped working.

**Comment by limansky** [comment]
As far as I remember it successfully compiles with Qt5. Which ebuild are you using? tinymount was removed from portage because it still depends on udisks-1 (which is still not deleted from portage btw, and even not masked).

**Comment by limansky** [comment]
Here is the reason https://bugs.gentoo.org/601358

**Comment by limansky** [comment]
I've created gist with ebuild for Qt5. https://gist.github.com/limansky/dc4635054805d237d909181dfb8b4bf4

**Comment by ghost** [comment]
It seems to work, thank you very much!
