### ISSUE TITLE
Regression: Tinymount incorrectly handle device mount/unmount status

### ISSUE THREAD

**Issue by tataranovich** [limansky/tinymount#7]
Tinymount failed to handle correctly device mount status. If you mount device from tinymount menu then it mounts it but still show device as unmounted. 

```
Adding device to cache: "/org/freedesktop/UDisks/devices/sdb1"
mountDevice: "/org/freedesktop/UDisks/devices/sdb1" 
Device changed: "/org/freedesktop/UDisks/devices/sdb1" 
Device "sdb1" is mounted to "/media/6933-1633" , status = 0
```

If you try to click on the same device then error appear:

```
mountDevice: "/org/freedesktop/UDisks/devices/sdb1" 
Device "sdb1" is mounted to "" , status = 3 
3 "Device is busy"
```

The same issue when you try to unmount already mounted device.

**Comment by limansky** [comment]
Do you mean, that it was introduced after my yesterday fixes?

**Comment by tataranovich** [comment]
Yes, yesterday I test the latest GIT snapshot from master (before writing my reports) and mount/unmount working fine.
