### ISSUE TITLE
6 "Unknown error"

### ISSUE THREAD

**Issue by yurror5634** [limansky/tinymount#8]
Hi!
I am interested in you program, but when I want to mount device there is an error:
mountDevice: "/org/freedesktop/UDisks/devices/sdd1" 
Device "sdd1" is mounted to "" , status = 6 
6 "Unknown error"

1) There is list of groups of my user:
user1 adm lp audio video plugdev lpadmin fuse kvm bacula debian-transmission wireshark
2) $ls -al /media
drwxr-xr-x  6 user1 user1 4096 Сен 20 17:51 .
drwxr-xr-x 26 root root 4096 Сен 19 11:38 ..
lrwxrwxrwx  1 root root    6 Май 14  2011 cdrom -> cdrom0
drwxr-xr-x  2 root root 4096 Май 14  2011 cdrom0
drwxr-xr-x  2 root root 4096 Май 14  2011 cdrom1
lrwxrwxrwx  1 root root    7 Май 14  2011 floppy -> floppy0
drwxr-xr-x  2 root root 4096 Май 14  2011 floppy0
3) In /usr/share/polkit-1/actions/org.freedesktop.udisks.policy I have change all "<allow_any>no</allow_any>" on "<allow_any>yes</allow_any>"
Sorry for my english. My best regards.

**Comment by vdudouyt** [comment]
That's also seems being reproduced on fresh Gentoo installations. Limansky, do you have any ideas?
My guess is that we should review the dependencies list.

**Comment by limansky** [comment]
Hi,

  I suppose it may be related with runtime requirements. I think you should ensure that consolekit daemon is started and consolekit session is launched. You can do it using ck-list-sessions. If the session is not started, you should start your window manager using ck-launch-session. E.g. it can be done in .xinitrc:

```
 exec ck-launch-session xmonad
```

(or any other WM you like)

**Comment by yurror5634** [comment]
Thank you, limansky! It is work!
For openbox ~/.xinitrc:
exec ck-launch-session openbox-session
